-- ============================================
-- Supabase Setup for MedRelief Contact Form
-- ============================================

-- ------------------------------------------------
-- PART 1: Create the patients table
-- ------------------------------------------------

-- Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  
  -- Personal Information
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  
  -- Appointment Details
  service TEXT NOT NULL,
  message TEXT NOT NULL,
  preferred_date TEXT NOT NULL,
  preferred_time TEXT NOT NULL,
  
  -- Medical Report
  medical_report_url TEXT,
  
  -- Status Tracking
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'scheduled', 'completed', 'cancelled')),
  notes TEXT
);

-- Enable Row Level Security (RLS) if not already enabled
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Allow public inserts" ON patients;
DROP POLICY IF EXISTS "Allow authenticated reads" ON patients;
DROP POLICY IF EXISTS "Allow authenticated updates" ON patients;

-- Create policies
CREATE POLICY "Allow public inserts" ON patients
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow authenticated reads" ON patients
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated updates" ON patients
  FOR UPDATE
  TO authenticated
  USING (true);

-- Create indexes
DROP INDEX IF EXISTS idx_patients_status;
DROP INDEX IF EXISTS idx_patients_created_at;
DROP INDEX IF EXISTS idx_patients_email;
DROP INDEX IF EXISTS idx_patients_service;

CREATE INDEX IF NOT EXISTS idx_patients_status ON patients(status);
CREATE INDEX IF NOT EXISTS idx_patients_created_at ON patients(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_patients_email ON patients(email);
CREATE INDEX IF NOT EXISTS idx_patients_service ON patients(service);

-- ------------------------------------------------
-- PART 2: Storage Bucket Setup (via Storage API)
-- ------------------------------------------------
-- NOTE: Storage buckets cannot be created via SQL.
-- Please create the bucket manually in Supabase Dashboard:
--
-- 1. Go to Supabase Dashboard → Storage
-- 2. Click "New Bucket"
-- 3. Enter: medical-reports
-- 4. Check "Make bucket public"
-- 5. Click "Create bucket"
--
-- Then run the policies below:
------------------------------------------------

-- Drop existing storage policies (if any)
DROP POLICY IF EXISTS "Allow public uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow public reads" ON storage.objects;

-- Policy: Allow anyone to upload files (for the contact form)
CREATE POLICY "Allow public uploads" ON storage.objects
  FOR INSERT
  TO authenticated, anon
  WITH CHECK (
    bucket_id = 'medical-reports' AND
    (storage.foldername LIKE 'patients/%' OR storage.foldername LIKE 'temp/%')
  );

-- Policy: Allow public read access to medical reports
CREATE POLICY "Allow public reads" ON storage.objects
  FOR SELECT
  TO authenticated, anon
  USING (
    bucket_id = 'medical-reports' AND
    (storage.foldername LIKE 'patients/%' OR storage.foldername LIKE 'temp/%')
  );

-- ------------------------------------------------
-- PART 3: Verification
-- ------------------------------------------------

-- Check patients table exists:
-- SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'patients';

-- Check RLS is enabled:
-- SELECT relname, relrowsecurity FROM pg_class WHERE relname = 'patients';

-- Check storage policies:
-- SELECT * FROM pg_policies WHERE policyname LIKE '%public%';

