-- ============================================
-- PART 1: Create the patients table
-- ============================================

-- Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  
  -- Personal Information
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  
  -- Appointment Details
  service TEXT NOT NULL,
  message TEXT NOT NULL,
  preferred_date TEXT NOT NULL,
  preferred_time TEXT NOT NULL,
  
  -- Medical Report
  medical_report_url TEXT,
  
  -- Status Tracking
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'scheduled', 'completed', 'cancelled')),
  notes TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;

-- Drop existing policies
DROP POLICY IF EXISTS "Allow public inserts" ON patients;
DROP POLICY IF EXISTS "Allow authenticated reads" ON patients;
DROP POLICY IF EXISTS "Allow authenticated updates" ON patients;

-- Create policies
CREATE POLICY "Allow public inserts" ON patients
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow authenticated reads" ON patients
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated updates" ON patients
  FOR UPDATE
  TO authenticated
  USING (true);

-- Create indexes
DROP INDEX IF EXISTS idx_patients_status;
DROP INDEX IF EXISTS idx_patients_created_at;
DROP INDEX IF EXISTS idx_patients_email;
DROP INDEX IF EXISTS idx_patients_service;

CREATE INDEX IF NOT EXISTS idx_patients_status ON patients(status);
CREATE INDEX IF NOT EXISTS idx_patients_created_at ON patients(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_patients_email ON patients(email);
CREATE INDEX IF NOT EXISTS idx_patients_service ON patients(service);

-- Verification
SELECT 'patients table created' AS status;

